### ISSUE TITLE
VMware Horizon Client på gnome3/nixos: Ikke støttet display server protocol

### ISSUE THREAD

**Issue by jhhhnikt** [HNIKT-Tjenesteutvikling-Systemutvikling/NixHNIKT#116]
Hvordan gjenskape:

1. Legg til `vmware-horizon-client` i home.packages listen: home/users/min-profil/default.nix.
2. Logg inn på https://workspace.helsenord.no/ og velg "Enkel tilgang VDI".

![image](https://github.com/HNIKT-Tjenesteutvikling-Systemutvikling/NixHNIKT/assets/130743650/681bc1df-7d7f-4d1b-98e2-029ca9b9c9c3)

**Comment by Gako358** [comment]
Klienten bruker x11 server, og Gnome er bruker wayland.
Løsningen er å velge browser, istedet for clienten.
