### ISSUE TITLE
Copilot CLI 

### ISSUE THREAD

**Issue by VebjornHal** [HNIKT-Tjenesteutvikling-Systemutvikling/NixHNIKT#86]
Kan du legge inn denne?

https://githubnext.com/projects/copilot-cli/

**Comment by Gako358** [comment]
![image](https://github.com/HNIKT-Tjenesteutvikling-Systemutvikling/NixHNIKT/assets/42249650/5001d80f-449c-4a74-b0d6-bbf188c9acab)


Dette må aktiveres av enterprise admin for å kunne bruke.
Er tilgjengelig i flake, men avventer med godkjenning.

**Comment by KristianAN** [comment]
Denne er skrudd på nå så vidt jeg kan se

**Comment by Gako358** [comment]
Det er korrekt, har lagt den til i flaket, kan vise hvordan bruke den i morgen.

<img src="https://media0.giphy.com/media/QMoXJjGPsmJ6Pdc596/giphy.gif"/>
